USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE TESTING_DB TO ROLE ROLE_TEST_ETL;
GRANT USAGE ON SCHEMA TESTING_DB.INTEGRAL_TEST TO ROLE ROLE_TEST_ETL;
GRANT INSERT, SELECT ON TABLE TESTING_DB.INTEGRAL_TEST.RANDOM_VALUES TO ROLE ROLE_TEST_ETL;
GRANT INSERT, SELECT ON TABLE TESTING_DB.INTEGRAL_TEST.random_values_mirror TO ROLE ROLE_TEST_ETL;